apiVersion: batch/v1
kind: Job
metadata:
  name: bmi-job
spec:
  template:
    spec:
      containers:
      - name: bmi-job
        image: yash5090/bmi:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
