apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: bmi
  template:
    metadata:
      labels:
        app: bmi
    spec:
      containers:
        - name: bmi
          image: yash5090/bmi:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
